# 应用服务 WEB 访问端口
server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://121.37.172.231:3306/ordering_food
    username: dingyouxiu
    password: dhp.666666
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000
